server:
  port: 8086
#  servlet:
#    context-path: /pro05
spring:
  mvc:
    hidden-method:
      filter:
        enabled: true
    static-path-pattern: /static/**
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    password: 1234
    username: root
    url: jdbc:mariadb://localhost:3306/tsherpa
  profiles:
    active: local
  thymeleaf:
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
    cache: false
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.chunjae.test07.entity
  mapper-locations: mappers/**/*.xml
logging:
  config: classpath:logback.xml
