server:
  port: 8080
spring:
  profile:
    active: local
  thymeleaf:
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  mvc:
    servlet:
      path: /
    static-path-pattern: /static/**
    hidden-method:
      filter:
        enabled: true
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/pro05
    username: root
    password: 1234
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB
      location: C://upload

  messages:
    basename: messages
    encoding: UTF-8
  mail:
    host: smtp.naver.com
    port: 465
    username: juncheol08@naver.com
    password: --
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.ssl.trust: smtp.naver.com
      mail.smtp.starttls.enable: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.tsherpa.team35.entity
  mapper-locations: mappers/**/*.xml

logging:
  config: classpath:logback.xml
  level:
    org:
      springframework: info

itemImgLocation: C:/team35/item
uploadPath: file:///C:/team35

